### ISSUE TITLE
Question about neutral model estimation

### ISSUE THREAD

**Issue by RenzoTale88** [CshlSiepelLab/RPHAST#1]
Good morning,
I'm contacting you for a question on how to define the neutral model. My situation is the following: I've generated multiple genome alignments for 5 assemblies using cactus. I would like to use these alignments to identify region under putative selective pressure using halPhyloP, function that require a set of regions under neutral selection. They suggested to detect them through ```hal4dExtract```, function that I can't use due to my assemblies being completely novel and still without an annotation that can be used to define such regions.
My question for you is the following: is there an alternative way to define the neutral model, or I have to wait for the annotation to be ready before run this function?

Thank you in advance
Andrea

**Comment by siepellab** [comment]
Hello Andrea, 
I am not familiar with  halPhyloP and hal4dExtract so I not sure how they would work. 
In RPHAST you can estimate a neutral model using phyloFit without a features/annotation file. For estimating a neutral model using phyloFit you need an alignment and a tree. 

You can find the details on how to use phyloFit in RPHAST here - http://compgen.cshl.edu/rphast/rphast-manual.pdf

Hope this helps!
Ritika

**Comment by RenzoTale88** [comment]
@siepellab thank you very much for your reply. Is it also possible to extract the regions of a target genome under neutral selection using these functions?

**Comment by siepellab** [comment]
Hi Andrea,
Unfortunately that is not possible using RPHAST.
Ritika

**Comment by RenzoTale88** [comment]
Ok thank you very much Ritika!
