### ISSUE TITLE
Unable to install RPHAST

### ISSUE THREAD

**Issue by DustinSokolowski** [CshlSiepelLab/RPHAST#3]
Hello! 

I noticed that RHPAST has been removed from CRAN and has a compilation error from github. Is the package still being maintained? 

Thanks!
Dustin

**Comment by sumin5784** [comment]
Hi, 

I'm also having the same issues. I tried installing both from git and source. Following is console error:

`
install.packages("C:/Users/sumin/Downloads/rphast_1.6.11.tar.gz", repos = NULL, type = "source", lib="C:/Program Files/R/R-4.1.0/library")
* installing *source* package 'rphast' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG       -I. -DHAVE_CONFIG_H -DPHAST_VERSION='"v1.4"' -DRPHAST -DR_LAPACK -DPCRE_STATIC -s -fno-strict-aliasing -DUSE_PHAST_MEMORY_HANDLER   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c stringsplus.c -o stringsplus.o
stringsplus.c:15:10: fatal error: pcre.h: No such file or directory
 #include <pcre.h>
          ^~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-41~1.0/etc/i386/Makeconf:238: stringsplus.o] Error 1
ERROR: compilation failed for package 'rphast'
* removing 'C:/Program Files/R/R-4.1.0/library/rphast'
Warning in install.packages :
  installation of package ‘C:/Users/sumin/Downloads/rphast_1.6.11.tar.gz’ had non-zero exit status
`

Any feedback would be great! Thanks.
