### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by emistasis** [CshlSiepelLab/RPHAST#9]
Hi!

I've been trying to install RPHAST onto my macOS machine for a bit now but haven't had any luck. I've poked through some of the closed issues already, and I wasn't able to find an answer. 😅 

I first tried using RStudio and got the following error message:
```
configure: error: Couldn't find pcre.h... download/install at www.pcre.org
ERROR: configuration failed for package ‘rphast’ 

removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rphast’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/yf/c222y8zd4xdfgn74tjwwn8zm0000gr/T//RtmpIdLMhT/fileb8b6d82b454/rphast_1.6.11.tar.gz’ had non-zero exit status
```

After receiving this error message, I installed pcre onto my machine using homebrew. The installation was successful. I used pkg-config to extract the metadata for pcre and got the following link flags:
`-I/opt/homebrew/Cellar/pcre/8.45/include -L/opt/homebrew/Cellar/pcre/8.45/lib -lpcre`

I also verified that the pcre.h file does exist at the following location: `/opt/homebrew/include/pcre.h`

I ran R in the terminal to install rphast but ran into the same error. I also tried using both [bioconda](https://anaconda.org/bioconda/r-rphast) commands to no avail. Any guidance or advice on how to troubleshoot this would be greatly appreciated. I'm happy to provide more info if needed.

Edit:
I should include I'm working with R version 4.3.1 and on a mac M1 Sonoma.

**Comment by rhassett-cshl** [comment]
@emistasis Using these commands in R to set environment paths to pcre has worked for me:

> Sys.setenv(CFLAGS = "/opt/homebrew/opt/pcre/include")
> Sys.setenv(LDFLAGS = "/opt/homebrew/opt/pcre/lib")

Let me know if this resolves the issue for you
